### ISSUE TITLE
ender_air.js causing crash when bonemealing

### ISSUE THREAD

**Issue by Electrofried** [TheDrOfDoctoring/generic-botania-pack#2]
Not sure if some weird interaction between the new bonemeal event that is checking for living root or not. Bonemeal was in offhand. Crash is reproducible. Logs below.  
 

https://gist.github.com/Electrofried/c8efc09bf42ba2772da2540efce00c2d

**Comment by TheDrOfDoctoring** [comment]
should be fixed by checking if the event is null in the commit 6889609
