### ISSUE TITLE
all custom ars crushing recipes have a 0% chance of success

### ISSUE THREAD

**Issue by saltyseadoggo** [TheDrOfDoctoring/generic-botania-pack#4]
all of this modpack's custom ars nouveau crushing recipes have a 0% success rate, as shown in emi. upon attempting to make a copper plate, for example, the ingot simply disappears.

![image](https://github.com/TheDrOfDoctoring/generic-botania-pack/assets/69029346/e33d9a4c-a4a4-4328-9c43-f42c8a01674b)

**Comment by TheDrOfDoctoring** [comment]
thanks for the report, seems like they were broken with a mod update, newest release on curseforge will have the fixed set of mods
